name: Build BulbMan APK

on:
  workflow_dispatch:   # lets you trigger manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip openjdk-17-jdk unzip git
        pip install buildozer cython

    - name: Unzip project
      run: unzip BulbManGame.zip -d BulbManGame

    - name: Build APK
      working-directory: BulbManGame
      run: |
        buildozer init
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: BulbMan-APK
        path: BulbManGame/bin/*.apk
